language: cpp
compiler:
 - gcc
 - clang
before_install:
 - sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-beta-proper
 - sudo apt-get update -qq
 - sudo apt-get install -qq valac uuid-dev libevent-dev libarchive-dev intltool re2c libjansson-dev libqt4-dev cmake
 - git clone --depth=1 --branch=release-2-11-3 https://bitbucket.org/tildeslash/libzdb.git deps/libzdb
 - git clone --depth=1 --branch=master git://github.com/haiwen/libsearpc.git deps/libsearpc
 - git clone --depth=1 --branch=master git://github.com/haiwen/ccnet.git deps/ccnet
 - git clone --depth=1 --branch=master git://github.com/haiwen/seafile.git deps/seafile
 # build libzdb, required by ccnet/seafile
 - cd deps/libzdb && ./bootstrap && ./configure --without-postgresql --without-mysql && make -j8 && sudo make install && cd -
 # build libsearpc
 - cd deps/libsearpc && ./autogen.sh && ./configure
 - make -j8 && sudo make install && cd ../..
 # build ccnet
 - cd deps/ccnet && ./autogen.sh && ./configure --enable-client --enable-server
 - make -j8 && sudo make install && cd ../..
 # build seafile
 - cd deps/seafile && ./autogen.sh && ./configure --disable-fuse
 - make -j8 && sudo make install && cd ../..
script:
 - cmake -DUSE_QT5=off .
 - make -j8
 - git clean -xfd
 - sudo apt-get purge libqt4-dev -qq && sudo apt-get autoremove --purge -qq
 - sudo apt-get install -qq qtsystems5-dev qttools5-dev qttools5-dev-tools qdbus-qt5 qtbase5-dev-tools qtbase5-dev qtsystems5-dev qtdeclarative5-dev
 - cmake -DUSE_QT5=on .
 - make -j8
notifications:
  email:
    recipients:
      - linshuai2012@gmail.com
      - rwindz0@gmail.com
